CREATE TABLE IF NOT EXISTS product (
	id UUID PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	price INTEGER NOT NULL DEFAULT 0,
	firm VARCHAR(20) NOT NULL,
	available BOOLEAN DEFAULT FALSE,
	local_date_time TIMESTAMP NOT NULL
)
